# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c5a751818f3df0e859ea332ae1c85dc2b451cd8454f73f9beb90ae2afc586217bdceb72c2d55a1c5c619db65df65aa245b3a03e3318940fb5f57be651591f84e

test:
  secret_key_base: e83b10c83f1422d41f128daece0766eb05eb78c97a41912114b1686431db224760145d2f2291e38ab5e3497e999439d78ab8b67c5b527bea6e6cc51fb476b9bf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
